const initialPosts = [
  {
    id: "V6u6kEkZbsa_shuSPUh3p",
    author: "Amelia Larkin",
    img: "http://lorempixel.com/640/480/cats",
    client: "Panasonic",
    media: "Weibo",
    date: "Wed Jun 02 2021 23:55:12 GMT+0800 (Hong Kong Standard Time)",
    post: "Post on Panasonic",
    sentiment: "Neutral",
    impact: 3,
    data: {
      likes: 62,
      comments: 99,
      laughs: 97,
      cries: 25,
      surprises: 42,
      angry: 68,
    },
  },
  {
    id: "d0OXV3RFgfKibai4G0kva",
    author: "Timmy Nikolaus",
    img: "http://lorempixel.com/640/480/cats",
    client: "Sony",
    media: "LinkedIn",
    date: "Wed Jun 09 2021 21:27:59 GMT+0800 (Hong Kong Standard Time)",
    post: "Post on Sony",
    sentiment: "Positive",
    impact: 0,
    data: {
      likes: 59,
      comments: 47,
      laughs: 70,
      cries: 31,
      surprises: 60,
      angry: 77,
    },
  },
  {
    id: "z3Zy3byfgPTsBubI4dM1x",
    author: "Jessie Zieme",
    img: "http://lorempixel.com/640/480/cats",
    client: "Apple",
    media: "HK01",
    date: "Post on Apple",
    sentiment: "Negative",
    impact: 1,
    data: {
      likes: 0,
      comments: 81,
      laughs: 12,
      cries: 93,
      surprises: 52,
      angry: 84,
    },
  },
];
