name: Deploy using AWS

on:
  push:
    branches: [master]

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install back end...
        run: npm install
      - name: Install front end...
        run: npm run client-install
      - name: Test front end...
        run: npm run client-test
      - name: Build front end...
        run: npm run client-build

      - name: AWS SSM Send Command
        uses: peterkimzz/aws-ssm-send-command@master
        with:
          aws-region: ap-southeast-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID  }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
          instance-ids: ${{ secrets.INSTANCE_ID  }}
          working-directory: /home/ubuntu/social-media-monitor
          command: /bin/sh ./deploy.sh
          comment: Deploy the master branch
