name: Deploy using AWS

on:
  push:
    branches: [master]

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: AWS SSM Send Command
        uses: peterkimzz/aws-ssm-send-command@master
        with:
          aws-region: southeast-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID  }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
          instance-ids: ${{ secrets.INSTANCE_ID  }}
          working-directory: /home/ubuntu/social-media-monitor
          command: /bin/sh ./deploy.sh
          comment: Deploy the master branch
